import "../../../validation/login-form-validation.ts"
import "../../../utils/animations/awing-effect.ts"
import "../../../styles/spinners.css"
import "../../../utils/animations/input-visibility-switcher.ts"
import "@/style.css"
